### ISSUE TITLE
HW-2

### ISSUE THREAD

**Issue by leshhub** [VARWA/todo#10]
## Форматирование кода
После прогона через `dart format` были изменены 11 (включая автоматически сгенерированные) файлов. Поскольку в более половины файлов форматирование присутствует, то снижать за это не буду.
```
Formatted lib\data\remote_data\dio_handler.dart
Formatted lib\generated\codegen_loader.g.dart
Formatted lib\generated\locale_keys.g.dart
Formatted lib\models\new_task_model.dart
Formatted lib\models\task_model.dart
Formatted lib\repository\entity\one_task_response.dart
Formatted lib\themes\src\constants.dart
Formatted lib\ui\change_task_screen\elements\importance_values.dart
Formatted lib\ui\main_screen\widgets\task_in_list_with_deadline_widget.dart
Formatted lib\ui\main_screen\widgets\task_in_list_without_deadline_widget.dart
Formatted lib\ui\main_screen\widgets\tasks_list_widget.dart
Formatted 38 files (11 changed) in 0.45 seconds.
```
На заметку: чтобы форматирование было более *красивым*, то в конце списка параметров добавляй запятую.
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/ui/main_screen/main_screen_widget.dart#L18-L23

## Реализация логики с бэкендом
Работа с бэком сводится только к получению списка задач, и при этом это функция не работает (закомментирована). Поскольку большая часть функционала (*post*, *put*, *delete*, *patch*) не реализована, то зачесть этот пункт не могу.

## Советы по коду

1. Поля модели желательно делать не мутабельными (неизменяемыми). В таком случае, при изменении поля модели нужно будет пересоздавать заного объект (с этим поможет добавления метода copyWith).
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/models/task_model.dart#L1-L10

2. Не стоит вносить какую-то бизнес-логику в уровень *models*. Поскольку в данном файле не создаются новые модели, а лишь производятся преобразования над другими, то лучше переименовать и переместить этот файл в папку *repository* (к примеру), на который будут ссылаться другие файлы. Тоже самое касается и файла *new_task_model.dart*.
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/models/task_list_model.dart#L71-L90

3. Файлы из папки *entity* являются скорее моделями, а не сущностями, поскольку привязаны к слою "data".
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/repository/entity/all_tasks_response.dart#L6-L24

4. Дублирование кода. Было бы лучше создать один виджет, который принимает в себы булевую переменную, и по ней решает, что отрисовать (через тернарное выражение, к примеру).
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/ui/main_screen/widgets/task_in_list_with_deadline_widget.dart#L27-L56
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/ui/main_screen/widgets/task_in_list_without_deadline_widget.dart#L24-L52

5. В коде 2 скрина обращаются напрямую к InheritedWidget, чтобы обратиться к методам по изменению списка задач. Это не совсем правильно, поскольку при добавлении ещё одной страницы, необходимо чтобы она тоже была под этим InheritedWidget-ом, и при разрастании проекта это может привнести некоторые затруднения. К тому же будет сложнее писать тесты. Будет неплохо, если применить внедрение зависимостей (DI, по ней недавно была трансляция [у другого потока](https://www.youtube.com/watch?v=yGiCNunSVN8)), и передавать в каждый скрин (или feature) объект, у которого будут методы для работы с БД, и уже от родителя их править/переопределять.
https://github.com/VARWA/todo/blob/99c8c82d70cd980927ed280d23bab8c0a2f5d4ad/lib/ui/change_task_screen/widgets/delete_task_widget.dart#L20-L24

**Comment by VARWA** [comment]
Большое спасибо за подробное ревью кода! Многое не знал, даже не догадывался. Про dart format, например, впервые услышал. Обязательно воспользуюсь рекомендациями, еще раз спасибо, Желаю удачи с проектом! 
P.S. Баллы в lms отмечены непроставленными, с нетерпением жду результатов)
