### ISSUE TITLE
Codereview homework #3

### ISSUE THREAD

**Issue by f1xgun** [VARWA/todo#12]
## Найденные недостатки:
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/data/local_data/db_handler.dart#L61  Я бы назвал insertTask, потому что в дальнейшем у тебя может быть больше сущностей, да и сейчас у тебя есть 3 таблицы, куда ты вставляешь - не узнаешь пока не залезешь внутрь. И вообще возможно стоит оставить в этом классе только методы по инициализации бд и созданию таблиц. Остальное вынести в менеджер/сервис.
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/data/local_data/db_handler.dart#L11 Если не ошибаюсь, то если так делать, то у тебя будет на каждый объект, который в себе создает инстанс логгер, новый объект логгера. 100 объектов, создающие логгер - 100 инстансов логгера. Создавай где-нибудь один раз инстанс логгера и используй его.
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/models/task_model.dart#L4 Лучше сделать enum с различными значениями, если использовать String, то очень легко ошибиться и всё сломается. Да и с перечислением сразу будет видно какие значения у тебя может принимать это поле
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/repository/data_client.dart#L15-L16 Если хочешь использовать DI, а не ServiceLocator, то нужно передавать используемые сервисы через аргументы в конструктор. Таким образом, класс не будет знать откуда и что ему надо получить.
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/repository/data_client.dart#L38-L42 для красоты можно сделать так:
```
    List<Task> newList = gotList.map(TasksParser.globalToLocalTaskParser).toList();
```
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/repository/data_client.dart#L48 Здесь можешь словить RuntimeError из-за обращение к несуществующему элементу массива. Стоит заменить <= на <
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/repository/data_client.dart#L56 Tasks, а не Task
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/data/local_data/db_handler.dart#L91-L103 Представляешь, что будет происходить при большом количестве данных? Смысл полностью перезаписывать таски, если большое количество тасок не изменяется
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/data/local_data/db_handler.dart#L142-L148 Не очень понял зачем тебе хранить все ревизии, достаточно хранить последнюю, которую ты будешь обновлять через update
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/repository/data_client.dart#L36 Лучше указать тип, иначе можно прокинуть что угодно. И может вылететь ошибка из-за обращения к несуществующему полю.
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/repository/data_client.dart#L170 Указать возвращаемый тип, в данном случае Future\<void>
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/models/task_list_model.dart#L26 Тоже самое про тип
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/models/task_list_model.dart#L34-L39 Можно сделать так:
```
List<Task> uncompletedTasks = _tasksList.where((element) => !element.done).toList();
```
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/models/task_list_model.dart#L44-L52 Тоже сахар:
```
int get completedCount =>_tasksList.where((element) => element.done).toList().length;
```
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/models/task_list_model.dart#L92 Тип у isNew
- https://github.com/VARWA/todo/blob/0833eb3a4a390ccad9495b32d1ca30f7f5182d9e/lib/models/new_task_model.dart#L23-L29 Поля класса и конструктор лучше писать в начале класса, чтобы было сразу видно какие поля имеет класс и какой конструктор
- Диплинк на создание новой таски не работает
- Очень долго приходится ждать любых действий, связанных с тасками. Выполнение таски может доходить до 5 секунд, пользователь может подумать, что приложение зависло
- Нет Unit тестов

Если есть вопросы - тг @f1xgun

**Comment by VARWA** [comment]
Большое Спасибо за подробный codereview! С замечаниями согласен, многое не знал/не учел, обязательно воспользуюсь твоими советами)
 Еще раз благодарю, Желаю успехов в работе над проектом!
