### ISSUE TITLE
Homework 4

### ISSUE THREAD

**Issue by vladdan16** [VARWA/todo#15]
### Чистота кода и общая структура проекта (5/5)
- Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (1/1)
- Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (1/1).
  - Коммент: Фактически, игноров нет, но issues есть. Кстати, какая версия flutter у тебя? Потому что на последней стабильной ты используешь deprecated методы.
```
warning • lib\ui\navigation\route_information_parser.dart:19:18 • The operand can't be null, so the condition is always
          'false'. Try removing the condition, an enclosing condition, or the whole conditional statement. •
          unnecessary_null_comparison
   info • lib\ui\navigation\route_information_parser.dart:17:39 • 'location' is deprecated and shouldn't be used. Use
          uri instead. This feature was deprecated after v3.8.0-3.0.pre. Try replacing the use of the deprecated member
          with the replacement. • deprecated_member_use
   info • lib\ui\navigation\route_information_parser.dart:56:31 • 'location' is deprecated and shouldn't be used. Pass
          Uri.parse(location) to uri parameter instead. This feature was deprecated after v3.8.0-3.0.pre. Try replacing
          the use of the deprecated member with the replacement. • deprecated_member_use
   info • lib\ui\navigation\route_information_parser.dart:64:35 • 'location' is deprecated and shouldn't be used. Pass
          Uri.parse(location) to uri parameter instead. This feature was deprecated after v3.8.0-3.0.pre. Try replacing
          the use of the deprecated member with the replacement. • deprecated_member_use
```
- Форматирование кода присутствует (1/1)
- Код разбит на фичи и слои (не важно, feature-first / layer-first) (2/2)

### Навигация, UI, animations (7/8)
- Навигация инкапсулирована в отдельной сущности, отсутствуют явные переходы `Navigator.push` прямо в колбеках (1/1)
- Текст длинных заметок обрезается по макету (1/1)
- Поддержка ночной темы (1/1)
- Реализованы анимации для добавления/исчезновения/редактирования и прочих взаимодействий с заметками (0/1)
- Реализована поддержка лендскейп-ориентации (2/2). 
  - Коммент: На самом деле, странный пункт, как по мне, ибо не сказали, как конкретно приложение должно выглядеть в таком случае. Судя по всему, ты не особо запаривался по этому поводу. Ну ровно как и я. Если я ошибаюсь, поправь.
- Реализована поддержка больших экранов (планшеты) (2/2). 

### Firebase (3/3)
- Реализована работа с Remote Configs, работает рантайм-переключение цвета важности (дефолтный красный по Фигме vs     #793cd8) (2/2)
- К проекту подключён и настроен Firebase Crashlytics, репортинг ошибок работает (1/1)

### Build & Release (8/8)
- Поддержаны 2 флейвора: для сборки тестинг и прод окружения. (2/2)
- Настроен CI на GitHub (4/4)
  - форматирование (+1)
  - линтер (+1)
  - тесты 
  - сборка (+1)
  - деплой (+1)
- Есть распространение через какой-то сервис вроде Firebase App Distribution (2/2).
  - Коммент: Мне интересно, получается ли у тебя скачать апку с firebase? Просто я получаю 403. Выглядит, как будто региональные ограничения гугла. Хотя и с впн тоже не работает.

### Разное (2/2)
- Добавлен инструмент для аналитики: Firebase/AppMetrica. Собирается аналитика по событиям: добавление, удаление, выполнение, переходы по экранам (1/1)
- Для дата-моделей используется пакет freezed (1/1)

### Итого (25/26)
Хочу отметить твою качественную работу. В целом все отлично, читать код приятно. Однако, настоятельно рекомендую изучить работу с гитом, в частности с гитхабом. А именно, проверяющему гораздо удобнее было бы ревьюить код в pull request'е, так как там можно увидеть отличия между текущей веткой и main -- проделанную работу, а не штудировать весь код. Также, командная работа практически не возможна без этого, так что такой навык очевидно пригодится во втором этапе Школы.

**Comment by VARWA** [comment]
Благодарю за code review! Очень приятно, что понравился код, над гитом да, поработаю. Данный warning не видел, спасибо, может действительно в версиях flutter различие, на проекте использовал 3.10.5. Если скачивать с firebase, то да, возникает та же ошибка, у меня работает с VPN (Planet VPN - France), для скачивания использовал приложение App Tester(вроде бы предлагается самим firebase, когда подтверждаешь почту). 
Ещё раз Спасибо! Удачи в учебе и изучении Flutter!
