### ISSUE TITLE
Кросс-проверка

### ISSUE THREAD

**Issue by aa1dar** [VARWA/todo#4]

**Comment by aa1dar** [comment]
Лучше создать отдельный фолдер 'widgets' и раскидать виджеты по отдельным файлам:
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/change_task_screen/change_task_screen_widget.dart#L248

https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/change_task_screen/change_task_screen_widget.dart#L199

**Comment by aa1dar** [comment]
Названия полей, переменных в Dart должны быть lowerCamelCase
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/models/task_model.dart#L6

https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/models/task_model.dart#L5

**Comment by aa1dar** [comment]
Тут анонимная функция должна обязательно вернуть что-то, хотя бы null:
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/main_screen/main_screen_widget.dart#L275-L283

**Comment by aa1dar** [comment]
Перед сдачей на проверку, выкладкой куда-либо хорошей практикой является использования команды: flutter analyze
![image](https://github.com/VARWA/todo/assets/53058708/5c2b6508-d159-4995-8a1a-00f9d950e4bf)

**Comment by aa1dar** [comment]
Эта строчка бросает exception:
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/change_task_screen/change_task_screen_widget.dart#L70

Менять состояние виджетов при построении виджетов очень плохая идея, по сути этот код работает так:
build -> setDeadlineStatus(true); && notifyListeners -> build ->  setDeadlineStatus(true); && notifyListeners  -> ...

Т.е. бесконечная перестройка виджетов. Поэтому лучше убрать вообще эту строчку и сделать true по-умолчанию тут:
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/change_task_screen/new_task_model.dart#L12

Если все таки используешь stateful widget, то тогда используй его преимущества, доступ к провайдеру можно получить уже в initState, доступ к настройкам маршрута можно получить в didChangeDependencies.

Также хорошей практикой является инициализация TextEditingContoller в полях класса, либо в initState. Также нельзя забывать его дизпоузать в методе dispose  stateful widget'а:
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/change_task_screen/change_task_screen_widget.dart#L66-L67
Из-за того что у тебя контроллер инициализируется в build методе, при любом изменении состояния виджета: переключения свитча, выбор приоритета - текст сбрасывается.

**Comment by aa1dar** [comment]
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/models/task_list_model.dart#L114-L123
это геттер, который возвращает значение, когда его вызывают, notifyListeners тут не нужен

**Comment by aa1dar** [comment]
Из-за того что считываешь провайдер через read() получается, что при удалении задачи происходит непредсказуемое поведение, если заменить на watch, удаление будет работать.
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/main_screen/main_screen_widget.dart#L56

Почитай про разницу между read и watch, когда что нужно использовать

**Comment by aa1dar** [comment]
А если список пустой, то возвращаем null? Что-то тут не то
https://github.com/VARWA/todo/blob/b9154f2e5e8b5afd9ff6467d57e7fd44b4cc4ece/lib/models/task_list_model.dart#L175-L182

**Comment by aa1dar** [comment]
Итого:

1. -1 балл за форматирование кода(не придерживался единого стиля написания кода где то camelCase, где то snake_case, 3 виджета в одном файле делает код менее читаемым)
2.  -5 баллов за верстку экранов(нет добавочных значков для низкого и высокого приоритета,
иконка глаза не того цвета, AppBar на главном экране в свернутом виде без иконки глазика, на странице редактирования/создания: слово Удалить уехало от иконки,  кнопка сохранить не соответствует макету, цвет текста даты не соответствует макету, кнопка DropdownButton вместе со стрелкой )
3. -1.5 балла за свайпы: при свайпе Выполнено задача не должна удаляться
4. -3 балла за показ выполненных дел с логикой - просто не реализовано

**Comment by VARWA** [comment]
> Итого:
> 
> 1. -1 балл за форматирование кода (не придерживался единого стиля написания кода, где используется camelCase, где используется snap_case, 3 виджета в одном файле делает код менее читаемым)
> 2. -5 баллов за верстку экранов(нет добавочных значков для оценки и высокого приоритета, 
>    иконка глаз не того цвета, AppBar на главном экране в свернутом виде без иконок глаз, на запрос/создание: слово Удалить уехало от иконок, кнопка выбора не требует макета , цвет текста в Европе не соответствует макету, кнопка DropdownButton вместе со стрелкой )
> 3. -1,5 балла за свайпы: при свайпе
> 4. -3 балла за показ выполненных дел с логикой - просто не реализовано

Большое спасибо за проверку! Еще большее спасибо за советы!!! Благодаря им у меня возникло более четкое понимание того, где и как нужно исправить, чтобы приложение заработало корректно
