### ISSUE TITLE
Проверка ДЗ 1

### ISSUE THREAD

**Issue by medvalna** [VARWA/todo#5]
Реузультаты проверки:
-0.5 за отсутствие ссылки на apk в ридми (апкшки вообще нигде в проекте нет)
-1: код не везде разбит на фичи/слои, 
-3: нет показа выполненного с логикой
-2: нет логирования
-4: нет иконки
---
Итого 15.5

**Comment by VARWA** [comment]
> 

Благодарю за проверку работы!

**Comment by VARWA** [comment]
> ## Реузультаты проверки:
> -0.5 за отсутствие ссылки на apk в ридми (апкшки вообще нигде в проекте нет)
> -1: код не везде разбит на фичи/слои,
> -3: нет показа выполненного с логикой
> -2: нет логирования
> -4: нет иконки
> Итого 15.5

У меня возник вопрос насчет иконок. На моем эмуляторе вроде все показывается, у тебя как-то иначе?

**Comment by medvalna** [comment]
Я смотрела только по коду и не нашла ничего про иконку.
Сейчас связалась со своим ментором, к вечеру проверим работу еще раз.

**Comment by medvalna** [comment]
Иконка найдена, баллы сейчас добавлю!
