### ISSUE TITLE
Проверка второго дз

### ISSUE THREAD

**Issue by SokoMix** [VARWA/todo#9]
Привет! Сборка приложения требует .env. Возможно, ты добавил эту папку в gitignore, поэтому я не могу запустить приложение.
<img width="1512" alt="image" src="https://github.com/VARWA/todo/assets/66212127/f6195f69-c41c-47df-b8e2-226b6e1ba86d">
Напиши мне в tg пожалуйста ник: @sokomix

**Comment by SokoMix** [comment]
Снял балл только за бэкенд. Есть пару замечаний, но они относятся больше к критериям прошлых ДЗ:
1) При нажатии на кнопку скрыть выполненные, они не скрываются
2) Свайп слева направо лучше помещать не в onDismissed. Смотри, onDismissed под капотом удаляет виджет из списка, чтобы этого избежать, лучше обрабатывать этот свайп в confirmDismiss, поскольку он не влечет за собой удаление и выглядит это не так костыльно
3) Почему-то при создании таска сразу выставляется дата 29 июня. Лучше тоже пофиксить, поскольку сценарий создания задания предполагает изначально выключенный свитчер даты.

А теперь несколько замечаний по критериям второго дз.
В модели есть места, где присутствует визуальная логика. Для чистоты архитектуры следует четко отделять слой визуальной логики от бизнес логики. Еще нужно контролировать форматирование кода для критерия (как бы выглядит все хорошо, но на будущее лучше не забывать про это, потому что мне проверяющий за это снял балл:)). Могу дать совет как я справился с задачей "не забывать про форматирование". Форматировать код можно командой dart format *path-to-file*, поэтому можно написать небольшой скрипт на bash, при запуске которого будет форматироваться код во всем проекте. Сделать это довольно несложно.
Удачи с проектом! Если есть вопросы, пиши в телегу.

**Comment by VARWA** [comment]
Большое Спасибо за подробное ревью! Обязательно воспользуюсь рекомендациями)) Тебе тоже удачи с проектом!
P.S. Твой контакт в телеге сохранил)
